### ISSUE TITLE
No 'location' returned when requesting ticket

### ISSUE THREAD

**Issue by yoeriboven** [lsapan/pgoapi-swift#1]
In the Alamofire.request in Auth.getTicket() no location is returned in `allHeaderFields` causing the app to crash.

**Comment by lsapan** [comment]
Are you experiencing this when you send an invalid username/password combination, or every time?

**Comment by yoeriboven** [comment]
Only with invalid credentials

**Comment by lsapan** [comment]
Ah okay, that makes sense. Thanks, I'll get it fixed up!
