### ISSUE TITLE
Cant use protocol

### ISSUE THREAD

**Issue by nguyenthanhcongsoict** [lsapan/pgoapi-swift#13]
![screen shot 2016-08-03 at 05 34 21](https://cloud.githubusercontent.com/assets/11443262/17347752/0c05e860-593c-11e6-8479-371a8d5a1343.png)
Sorry but i dont know why i alway get this :(

**Comment by lsapan** [comment]
You're telling Xcode that your ViewContoller confirms to the protocols, but it doesn't. For example to be a PGoAuthDelegate, your ViewController must implement didReceiveAuth and didNotReceiveAuth. Check out Example/PGoApi/ViewController.swift to see what I mean.

**Comment by nguyenthanhcongsoict** [comment]
thank you for support :D but one more question : Why i cant get Suggest when i type code ? hmm maybe i need clean and rebuild for new indexing form xcode ?

**Comment by lsapan** [comment]
No problem! Hmm, it should be suggesting it. Try cleaning and fully compiling the app. It should work after that. If not, maybe try restarting Xcode.

**Comment by nguyenthanhcongsoict** [comment]
again,big thanks for you. Really really good :) I should try to learning about code :) im really noob :/
