### ISSUE TITLE
Support for making API requests with difference accounts

### ISSUE THREAD

**Issue by mikezliu** [lsapan/pgoapi-swift#14]
Currently PGoAuth is a singleton.  It would be nice if it was not a singleton and the library supported making requests using different accounts.  Perhaps PGoApiRequest.makeRequest can be changed to accept a PGoAuth instance w/ the user.  Currently the API seems to be rate limited, and we can only make one request using one account per ~5 seconds.

**Comment by spinach** [comment]
+1

**Comment by lsapan** [comment]
Great idea, implementing it right now.
