### ISSUE TITLE
Multiple Logins not working

### ISSUE THREAD

**Issue by victorlandeira** [lsapan/pgoapi-swift#16]
Hi all,
Thanks for sharing this with us.
i have this huge array of users and i log in and scan multiple times. (building the spiral)
i can get the first right but then getMapObjects always fail

I tried to look into request headers and they look the same every request
any suggestion?

**Comment by lsapan** [comment]
@victorlandeira glad you got it working! I'd love to integrate a spiral search algorithm directly into the library, would you be willing to share your code?

**Comment by spinach** [comment]
+1

**Comment by victorlandeira** [comment]
i'm still getting on login response:
NSLocalizedFailureReason = "JSON could not be serialized. Input data was nil or zero length."
and code 302.

I'd love to! 
just started from python code

**Comment by lsapan** [comment]
Interesting, can you post the code that's generating that error?

**Comment by lsapan** [comment]
Closing in favor of #22 as it has more detail.
