### ISSUE TITLE
Google Auth 

### ISSUE THREAD

**Issue by billymwlei** [lsapan/pgoapi-swift#17]
Just quick question any plan for Google Auth?
Or I can help

**Comment by lsapan** [comment]
Google auth is implemented.

```
let auth = GPSOAuth()
auth.login(...)
```

**Comment by billymwlei** [comment]
Thanks :D

**Comment by aliasdoc** [comment]
What about  username and password with GPSOAuth ? gmail oauth authorization flow don't require credentials... thanks.

**Comment by tomalbrc** [comment]
@aliasdoc wut

**Comment by aliasdoc** [comment]
@tomalbrc ???
