### ISSUE TITLE
Use SwiftLint?

### ISSUE THREAD

**Issue by aust** [lsapan/pgoapi-swift#19]
I was thinking we could use SwiftLint on this project to keep the code consistent and manageable for everyone.

**Comment by westerlund** [comment]
In my opinion, a Swift lint wouldn't make any difference but slow down the project. I succest writing a set of rules to follow instead.

**Comment by aust** [comment]
Using SwiftLint would prevent the need for everyone to come up with a list of rules. Imagine all the time spent discussing a custom rule document that people have to abide by. Running SwiftLint on each PR would be a lot faster than manually checking the rules document against the code. SwiftLint comes with some pretty good default rules and is extremely simple to set up.

**Comment by lsapan** [comment]
I think this makes sense. I don't have time to personally implement it, but @aust would you be able to submit a PR for it? We'll need to tweak some of the defaults due to the nature of working with protos.
