### ISSUE TITLE
Spiral Search Algorithm

### ISSUE THREAD

**Issue by nbwar** [lsapan/pgoapi-swift#20]
Discuss implementation of Spiral search algorithm for getMapObjects

**Comment by PokemonGoSucks** [comment]
Are you delaying your requests by 10 seconds?

**Comment by nbwar** [comment]
I'm only sending one request. Would it be recommended to send multiple requests in a spiral pattern every 10 seconds? or is there a better way to get cells in a circular pattern vs what seems to be linear off of 1 request.

**Comment by PokemonGoSucks** [comment]
The way most apis get the cells is rectangular like http://s2map.com/ so it will look like a block on a map. What you're asking for is neighbouring cells, which is how the actual app does it. You can generate your own cells and input it into getMapObjects too.

Yes, you should send multiple requests in a spiral, separated by 10 s.

**Comment by lsapan** [comment]
@PokemonGoSucks if you have a working spiral algorithm, would you be willing to share it? This question comes up a lot, and it'd be great to have a central scanning algorithm that we can all build upon / improve.

**Comment by nbwar** [comment]
Thanks for the info. We should probably build a spiral search algorithm into this api. Are you already working on one? If not I'll work on one tonight after work. Also, I'm thinking multi account scanning will be crucial to avoid the 10s delay.

**Comment by PokemonGoSucks** [comment]
I made a location util based off corelocation that gets coordinates/bearing/distance and it shouldn't be too hard to add the spiral off of that. I'll PR the utils and we can figure this out.

**Comment by lsapan** [comment]
Okay, also @nbwar it looks like you have a bit of an app going. I created an app called Pokemapp (check my page) that's already fully functional with a bunch of features. The catch is it's dependent on the python server. Now that this library is more usable though, it should be trivial to just swap out the data source with this.

**Comment by rlburkes** [comment]
I am working on an algorithm that computes the minimum number of 70m radius disc that encompass all nearby spawn points. Using the algorithm I am able to cover all possible spawn locations in roughly 1/4 the requests(this varies based on spawn point density) it would take with the naive approach(querying around every spawn point), and roughly 1/10th the requests it would take via a spiral or spread approach. The worst case scenario is the same as the spread or spiral approach which would only occur if your map were uniformly covered by spawn points. 

The current algorithm isn't even optimized, it simply iterates through spawn points attempting to cover each with a 70m disc, unless the point is already covered by another disc. You could optimize the approach to use the minimum number of discs*, although the current approach is fast enough to make accounts the major bottleneck. I will see if I can clean up the code and open a PR, although it is currently tied to the rendering of the map which seems less than ideal. 
- Imagine exactly 2 spawn points one at 0,0 and one at 0,71 the current approach would cover the first point (0,0) and everything up to (0, 70) on the x axis.The point at 0,71 would be uncovered and require a second disc. These two points are only 71m apart so a 140m diameter circle can certainly cover both, but it vastly complicates the algorithm to compute this version.

**Comment by PokemonGoSucks** [comment]
@rlburkes If you mean the example app, then feel free to modify the example in any form.
