### ISSUE TITLE
Crashing error after login

### ISSUE THREAD

**Issue by MatthewFrench** [lsapan/pgoapi-swift#21]
![screen shot 2016-08-03 at 12 08 00 pm](https://cloud.githubusercontent.com/assets/9086152/17375892/a4e9f364-5978-11e6-9ef5-412b64d8bf0c.png)
This code looks awesome, after login this happens. Any idea why?

**Comment by PokemonGoSucks** [comment]
See the solution I posted in #10 . Just replace s2geometry with that code.

**Comment by lsapan** [comment]
@PokemonGoSucks man you're fast! Closing as duplicate of #10.
