### ISSUE TITLE
Getting the pokenmons a player having in player profile

### ISSUE THREAD

**Issue by billymwlei** [lsapan/pgoapi-swift#24]
Just quick question, how get the Pokenmon and it's value like CP from Player profile ?

**Comment by rowellx68** [comment]
You will have to request for the player inventory. Here's what I've done to achieve that. 

https://github.com/rowellx68/pgorate/blob/master/pgorate/ViewController%2BAuth%2BPGOApi.swift#L40

**Comment by lsapan** [comment]
Thanks for sharing @rowellx68!
