### ISSUE TITLE
Accessing Level, distance walked and prestige

### ISSUE THREAD

**Issue by vinced45** [lsapan/pgoapi-swift#26]
Has anyone been able to access any of these attributes from the API. I haven't been able to as of yet. Thanks

**Comment by rowellx68** [comment]
It seems that we already receive this as part of the GetInventory call. I can't understand why they would do this, wouldn't it have been better to lump it with the GetPlayer results?

Anyway, check the inventory for it and it's under `inventoryItemData.playerStats`. 

https://github.com/rowellx68/pgorate/blob/b5e19ede7e0100c4f610e2dfc7a5f8e17ea20896/pgorate/InventoryUtilities.swift#L22

EDIT: Added link to example
EDIT 2: New link -_-

**Comment by lsapan** [comment]
Thanks @rowellx68!

**Comment by vinced45** [comment]
Thanks @rowellx68
