### ISSUE TITLE
Best way of using pgoapi-swift

### ISSUE THREAD

**Issue by rowellx68** [lsapan/pgoapi-swift#3]
Hi! Thanks for getting started with this.

I'm wondering what the best way of using this api? Currently, I'm having to copy over the classes/files into my own project and using it that way.

I'm making a Pokémon Rater, putting it up on git soon.

**Comment by lsapan** [comment]
Hey! Glad you're finding it useful. I'll be adding it to Cocoapods soon, so that'll definitely be the easiest way. For now though, you could open the project separately, compile the framework, and then add the framework to your project. That's probably the cleanest way to do it, and it means you won't need to delete all the files once it is on Cocoapods.

**Comment by rowellx68** [comment]
https://github.com/rowellx68/pgorate

For now, I've opted to copy the files. Just currently dealing with login. I was going to implement the Google login, but the python versions of the api aren't so descriptive.

**Comment by YufeiG** [comment]
@Isapan I can't seem to built it using it as a framework. All the methods and properties that should be used from externally should have the public keyword. After I added the public keywords, I get this error:

> Undefined symbols for architecture x86_64:
>   "type metadata accessor for ProtocolBuffers.GeneratedMessage", referenced from:
>       PogoSwift.ViewController.didReceiveApiResponse (pgoapi.ApiIntent, response : pgoapi.ApiResponse) -> () in ViewController.o
>       type metadata accessor for [ProtocolBuffers.GeneratedMessage] in ViewController.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Am I using this wrong? Could I use it without adding "public"?

**Comment by lsapan** [comment]
@YufeiG no actually you're right. I've been meaning to update it to work properly as a framework and be installed with Cocoapods, but I've been more focused on getting `getMapObjects` to work. I'll get there though! For now you can do as Rowell did and just copy the files. I'll update here when it's ready.

**Comment by rtlnr** [comment]
Niantic is blocking logins from cloud hosters now. Time for something native! :)

**Comment by lsapan** [comment]
I've restructured the project as a CocoaPod, so it should be much easier to use now! I'll get some installation instructions written up shortly.
