### ISSUE TITLE
[Request API]

### ISSUE THREAD

**Issue by nguyenthanhcongsoict** [lsapan/pgoapi-swift#30]
Why i cant use "upgradePokemon" while i can get inventory data and player data ? maybe i should wait for new API ?

**Comment by VergaraF** [comment]
The new API is up on running but I am aware this project is not up to date... so it is not working as it should

**Comment by nguyenthanhcongsoict** [comment]
ya, maybe he will comeback ?

**Comment by tomalbrc** [comment]
Have you read #23? Be patient & make sure to checkout similar issues before opening a new one
