### ISSUE TITLE
use cocoapods "no such module PGoA"

### ISSUE THREAD

**Issue by liubojiequan** [lsapan/pgoapi-swift#31]
Open PGoApi.xcworkspace ,and import framework like this
![2016-08-11 5 54 06](https://cloud.githubusercontent.com/assets/5020592/17585164/c4117044-5fec-11e6-9238-bf4c46d152f4.png)
but ViewControlle.swift import PGoA has error 
"no such module PGoA"
can you help me about it

**Comment by PokemonGoSucks** [comment]
I think you already figured out the problem, it should be PGoApi
