### ISSUE TITLE
fatal error: cannot increment endIndex

### ISSUE THREAD

**Issue by kwyk** [lsapan/pgoapi-swift#36]
Hi,
**i am getting the below error:** 
fatal error: cannot increment endIndex

**While doing:**
request.getMapObjects()
request.makeRequest(.GetMapObjects, delegate: self)

**Below is the output:**
Processing PGoApiMethod(id: .GetMapObjects, message:  cellId[0]: 3592208081102407973
 cellId[1]: 3592208082176149797
 cellId[2]: 3592208083249891621
 cellId[3]: 3592208084323633445
 cellId[4]: 3592208085397375269
 cellId[5]: 3592208086471117093
 cellId[6]: 3592208087544858917
 cellId[7]: 3592208088618600741
 cellId[8]: 3592208089692342565
 cellId[9]: 3592208090766084389
 cellId[10]: 3592208091839826213
 cellId[11]: 3592208092913568037
 cellId[12]: 3592208093987309861
 cellId[13]: 3592208095061051685
 cellId[14]: 3592208096134793509
 cellId[15]: 3592208097208535333
 cellId[16]: 3592208098282277157
 cellId[17]: 3592208099356018981
 cellId[18]: 3592208100429760805
 cellId[19]: 3592208101503502629
 cellId[20]: 3592208102577244453
 sinceTimestampMs[0]: 0
 sinceTimestampMs[1]: 0
 sinceTimestampMs[2]: 0
 sinceTimestampMs[3]: 0
 sinceTimestampMs[4]: 0
 sinceTimestampMs[5]: 0
 sinceTimestampMs[6]: 0
 sinceTimestampMs[7]: 0
 sinceTimestampMs[8]: 0
 sinceTimestampMs[9]: 0
 sinceTimestampMs[10]: 0
 sinceTimestampMs[11]: 0
 sinceTimestampMs[12]: 0
 sinceTimestampMs[13]: 0
 sinceTimestampMs[14]: 0
 sinceTimestampMs[15]: 0
 sinceTimestampMs[16]: 0
 sinceTimestampMs[17]: 0
 sinceTimestampMs[18]: 0
 sinceTimestampMs[19]: 0
 sinceTimestampMs[20]: 0
 latitude: 1.37510959630346 
 longitude: 103.897240851101 
, parser: (Function))...
fatal error: cannot increment endIndex

**Comment by vinced45** [comment]
make sure you are passing your location with each request. I was getting this error as well until I added it.

**Comment by kwyk** [comment]
Thanks for the reply.
I have tried passing the location on that request and still encountering the same error.

I did a pod update before. It was working before i update it.

**Comment by kwyk** [comment]
After i track the error. It came from this code:
**in hashLocation():**
if self.api.Location.alt == nil {
            LocationData.appendData(locationToHex(0)) **<< Commented out this currently to let it pass through to get data.**

**in locationToHex():**
let r = s.startIndex.advancedBy(i)..<s.endIndex.advancedBy(x)

**Comment by PokemonGoSucks** [comment]
You need to include an altitude. New update already addressed this. Despite what the example says, it is not optional.

**Comment by kwyk** [comment]
Thank you for your reply.
Ah so that's why it is not working.

**Comment by marioacarvalho** [comment]
@PokemonGoSucks Where do I need to include an altitude? Can't get any data since `pod update`

**Comment by westerlund** [comment]
`setLocation(latitude: Double, longitude: Double, altitude: Double? = nil)` is available on `PGoApiRequest`. Altitude is defined as an optional but you need to include it.

You just add the `altitude` parameter.

```
request.setLocation(location.latitude, longitude: location.longitude, altitude: location.altitude)
```
