### ISSUE TITLE
Answer: Google auth

### ISSUE THREAD

**Issue by sirgalleto** [lsapan/pgoapi-swift#4]
Do you have any info about Google credentials?

**Comment by rowellx68** [comment]
Somebody will need to port this https://github.com/vemacs/GPSOAuthSharp over to Swift

**Comment by affix** [comment]
I'm half way through doing google auth using GPS and Google Open Source frameworks

**Comment by sirgalleto** [comment]
I actually use with react-native a web view with web credentials and oAuth 2 in the new release of [PikaPika](www.facebook.com/pikapika42) 

Anyone would like to enter the beta testing?

**Comment by PokemonGoSucks** [comment]
I did an implementation:
https://github.com/PokemonGoSucks/pgoapi-swift/blob/master/pgoapi/gpsoauth.swift

**Comment by rowellx68** [comment]
@PokemonGoSucks re-wrote it to use Alamofire since the rest of the API is using it anyway. Thank you so much for implementing it 👍 

https://github.com/rowellx68/pgorate/blob/master/pgorate/pgoapi/gpsoauth.swift

**Comment by lsapan** [comment]
Thanks a bunch guys for getting Google Auth going. I'm going to refactor the library a bit to make it easier to use and include an example app. Any chance one of you can submit a PR for Google Auth? Thanks!

**Comment by rowellx68** [comment]
I could do that. Might refactor Auth and take out PtcAuth as it's own class. A few other strings will need to be made constants

**Comment by lsapan** [comment]
Yes that would definitely make the most sense.

**Comment by lsapan** [comment]
Closing as this has been implemented by @rowellx68, thanks!
