### ISSUE TITLE
How to import PGoApi in Cocoa Project

### ISSUE THREAD

**Issue by subzerofun** [lsapan/pgoapi-swift#42]
Hey thanks for porting the pgo-api to Swift!

I would really like to write an Cocoa app for account management and some map scanning functions (to generate coordinates for beehive clusters like this: [https://beehive.bessei-it.eu/](https://beehive.bessei-it.eu/) )

Could you give me short step-by-step tutorial how i could set up a new XCode Cocoa Project that correctly imports the PGoApi framework? Alamofire has a Cocoa framework too, that shouldn´t be a problem. But i have no idea about ProtocolBuffers...

**Comment by PokemonGoSucks** [comment]
Are you using cocoapods? [See the readme for instructions.](https://github.com/lsapan/pgoapi-swift#installation)

If not, the easiest way to start is to simply clone/download and open the xworkspace file. From there, you can scrap the example app.

**Comment by subzerofun** [comment]
Uh i meant how can i import the API for an Desktop (OSX, macOS) Cocoa Application 😄

I´m familiar with pods, but i unfortunately i get this error when i try to install it that way:
```
$ pod install
Analyzing dependencies
Pre-downloading: `PGoApi` from `https://github.com/lsapan/pgoapi-swift`, branch `master`
[!] The platform of the target `PgoApi-Desktop` (OS X 10.10) is not compatible with `PGoApi (0.1.0)`, which does not support `osx`.
```

**Comment by PokemonGoSucks** [comment]
Hey, sorry I misread your question. I added OS X support to the pod file so try again.

**Comment by subzerofun** [comment]
thanks will try it out! this api library is heaven-sent, since i´m only able to read and understand the python and js based apis that are out there, but unfortunately i´m not that experienced to write a python or js app from scratch.

since swift is so damn easy to learn (and fun to use, compared to other languages) i can´t thank you enough for all the effort you´ve put in this project.

i hope a lot of OSX & iOS devs will use your api and rewrite some existing map scanners projects. not with all the functions (like PokemonGo-Map), but something clean and simple.
i´m already so tired of all the python command line typing and remembering all the different arguments for each project... with xcode you can create a nice GUI quite fast and eliminate all that redundant typing.

i´ll try to write a little app for testing and learning purposes. i will start to with an user account manager that is able to pull workers from a file and use them to scan a small part of my city. with a nice GUI on top. let´s see how far i come with this 😄.

i´ve already written something like this with functions for generating python strings, coordinates, and an account database. now i can extend it in app without switching to python. it´s just a work in progress, but already save me a lot of time.

![accmanager](https://cloud.githubusercontent.com/assets/17863119/18066537/2eb0e1c8-6e39-11e6-9e1c-673134c2c403.png)

**Comment by PokemonGoSucks** [comment]
Nice, let me know if you run into anymore trouble!
