### ISSUE TITLE
No pokemons found

### ISSUE THREAD

**Issue by aliasdoc** [lsapan/pgoapi-swift#46]
Hi, I can't see any pokemons, just spawnpoints, gyms, pokestops, ... but when I launch official app, I can see there are 3 pokemons around me...
Is there an extra api call for pokemons ??
Thanks.

**Comment by DevelopIdeas** [comment]
Hi,

I also experienced this issue for a while and the solution for me was to check the "banned" property of the auth instance, Ninantic had banned my account.

Hope it helps.

**Comment by PokemonGoSucks** [comment]
The problem is that the api gets the map objects in a way that can miss pokemon. I am looking into rewriting parts of S2geometry.

If you find any coordinates that have this problem, please let us know!

**Comment by PokemonGoSucks** [comment]
I added the missing parent function to s2, so now the cells are finally correct. [If you are on the edge of certain cells, you can miss pokemon.](http://s2map.com/#order=latlng&mode=polygon&s2=true&points=9263822733559463936,9263822735706947584,9263822737854431232,9263822740001914880,9263822742149398528,9263822744296882176,9263822746444365824,9263822748591849472,9263822750739333120,9263822752886816768,9263822755034300416,9263822757181784064,9263822759329267712,9263822761476751360,9263822763624235008,9263822765771718656,9263822767919202304,9263822770066685952,9263822772214169600,9263822774361653248,9263822776509136896) In the future, we will need to add getEdgeNeighbours into our S2.

**Comment by aliasdoc** [comment]
Hi @PokemonGoSucks , thanks, you make a very good job for this library !!
