### ISSUE TITLE
Auth token has expired.

### ISSUE THREAD

**Issue by DevelopIdeas** [lsapan/pgoapi-swift#47]
Hi,

I am using a single instance of PoGoAuth (PTC Login) for my authentication and a single instance of PGoApiRequest. Everything is working as expected except after some time I get "Auth token has expired." for any request I make.

I've looked through the source code and I can't seem to find a refresh token method? Should I be using a new instance of PGoApiRequest for every request I make instead or is there something I've missed?

Thanks.

**Comment by tomalbrc** [comment]
I always use a new instance of PGoApiRequest

**Comment by PokemonGoSucks** [comment]
Right, there isn't a refresh method to relogin. I think it should be added.

**Comment by DevelopIdeas** [comment]
I've tried using the new request object for each request but it doesn't work, and after digging further into the code its got nothing to do with it anyway.

Is there an immediate solution at present or does a refresh function need adding?

I'd be happy to contribute if pointed in the right direction.

**Comment by PokemonGoSucks** [comment]
There isn't an immediate solution unless you want to make a new auth object and login again. Not sure how the actual app handles it either.

With PtcOAuth you can set auth.authToken to nil and it'll work. With google, the access ticket might be expired so you'll have to relogin.

**Comment by PokemonGoSucks** [comment]
If you want to try, just add this above makeRequest.

```
    public func refreshAuthToken() {
        self.auth!.authToken = nil
    }
```

And then replace expired = true with:

```
if self.auth!.authToken != nil {
                if (self.auth!.authToken?.expireTimestampMs < getTimestamp()) {
                    refreshAuthToken()
                    print("Auth token has expired. Getting a new one.")
                }
            }
```

**Comment by PokemonGoSucks** [comment]
I included it into my last PR.
