### ISSUE TITLE
Crash on S2Geometry lsb() -> UInt64

### ISSUE THREAD

**Issue by lucamegh** [lsapan/pgoapi-swift#5]
A crash occurs when executing this function inside S2Geometry.swift

`func lsb() -> UInt64 {
        return UInt64(Int64(id) & -Int64(id))
    }`

**Comment by lsapan** [comment]
What's the value of `id` for the cell you're testing with?

**Comment by lucamegh** [comment]
Id "9263822755068982677"

Luke, do you think it is wise/safe to publish an app on the App Store containing this unofficial API? The app would be free with in-app purchases.

**Comment by spinach** [comment]
@lsapan Link to SO where @lucamegh asked this question:
http://stackoverflow.com/questions/38623251/crash-on-uint64-bitwise-operation-in-swift

that will help solve the crash, but we still can't find useful map objects (expected since you said there's still some things to be done.)

**Comment by lsapan** [comment]
This should be all set now, let me know if you're still running into any issues.
