### ISSUE TITLE
Swift 3.0 conversion

### ISSUE THREAD

**Issue by DottD** [lsapan/pgoapi-swift#50]
Is it possible to have a Swift 3.0 conversion of the library?

**Comment by PokemonGoSucks** [comment]
Most of it can be converted, but I'm not sure about the dependencies. Another issue are the protos.. I'm also not entirely familiar with Swift 3. So, help is needed.

**Comment by PokemonGoSucks** [comment]
Change of mind: I am working on it.

**Comment by DottD** [comment]
Thank you! If it can help I saw that all of the dependecies are already converted in Swift 3.0. I can also help you a bit with the conversion, but I regret I have not so much time to work on it.

**Comment by sund4nce** [comment]
I can also help you out. Are you available via the pogodev discord channel?

**Comment by PokemonGoSucks** [comment]
@mort3m I'll join the discord tonight. Here is what I've got so far: https://github.com/PokemonGoSucks/pgoapi-swift/tree/Swift3.0

I'll try to figure out the empty map response issue tonight. It may be an issue with the hashing.

**Comment by PokemonGoSucks** [comment]
My branch works if you set checkChallenge in setApiSettings to false. I am redoing location fixes and adding a few more things before PR.
