### ISSUE TITLE
Compiler error from "PGoUtils.swift" - OSX only [bug]

### ISSUE THREAD

**Issue by subzerofun** [lsapan/pgoapi-swift#52]
Hey thanks for addition of OSX support to the pod! (i was the one asking for it in [Issue #42](https://github.com/lsapan/pgoapi-swift/issues/42))

I tried to compile my project with the updated pod, but in the File PGoUtils.swift, at line 3:
```swift
import AddressBookUI
```

 an iOS only Framework gets imported. Since there is no equivalent Framework for OSX/macOS the function `ABCreateStringWithAddressDictionary` at line 45 isn´t defined:
```swift
let location = CLLocation(latitude: latitude, longitude: longitude)
CLGeocoder().reverseGeocodeLocation(location, completionHandler: {(placemarks, error) -> Void in
    if placemarks?.count > 0 {
        let addressDictionary = placemarks![0]
       // right there:
        let address = ABCreateStringWithAddressDictionary(addressDictionary.addressDictionary!, false)
        completionHandler(location: address.stringByReplacingOccurrencesOfString("\n", withString: ", "))
    }
})
```

I tried to replace the framework, but i could just find [an old Obj-C library](https://developer.apple.com/library/mac/documentation/UserExperience/Reference/AddressBook/ObjC_classic/) that doesn´t provide the function needed.

So for now i have just uncommented the block with ```ABCreateStringWithAddressDictionary``` and everything compiles fine.
 But since the function `CLGeocoder` is also needed right below in 
```swift  
 public func reverseGeocode(...) {
        (...)
        let geocoder = CLGeocoder()
        (...)
}
```
could that render the API unusable for me? 
Since i had to uncomment everything that happens in `func CLGeocoder`... and then that function is referenced in ```reverseGeocode``` and doesn´t compute anything...

Is this function essential for map queries? If it is – please help me to find a solution for OSX.

**Comment by PokemonGoSucks** [comment]
This is non-essential code and can be commented out. I will go ahead and remove this from the utils and find an alternative.

**Comment by subzerofun** [comment]
My aim is to write a little Swift App that uses the OSX MapKit Framework to display the positions of multiple users (and give live feedback about found pokemon) – a simple map scanner basically (a reduced version of the PokemonGo-Map project).

Won´t i run into problems with getting map coordinates if i uncomment this line?

**Comment by PokemonGoSucks** [comment]
Nope. You can delete the entire file if you need to. It's just extra stuff to help build bots/scrappers.

**Comment by subzerofun** [comment]
OK, thanks. Also thanks for the rewritten PGoUtils.swift!
