### ISSUE TITLE
FortSearch always return OutOfRange

### ISSUE THREAD

**Issue by acer915** [lsapan/pgoapi-swift#53]
Hi

send:
Generating main request...
Generating subrequests...
Processing PGoApiMethod(id: .FortSearch, message:  fortId: 758c93d850ac49a183b6e5aa244c342e.16 
 playerLatitude: 25.033085 
 playerLongitude: 121.535516 
 fortLatitude: 25.033104 
 fortLongitude: 121.535702 
, parser: (Function))...
Building request...
Got a response!

Get:
result OutOfRange

branch PreVersion35 is ok.

thanks.

**Comment by PokemonGoSucks** [comment]
I just tested it and it worked for me. Make sure you setLocation closer to the fort.

**Comment by acer915** [comment]
Hi 

request.setLocation(fortData.latitude, longitude: fortData.longitude)
request.fortSearch(fortData.id, fortLatitude: fortData.latitude, fortLongitude: fortData.longitude)
request.makeRequest(.FortSearch, delegate: self)

I set same location for "setLocation" and "fortSearch", but always return OutOfRange

Have any I am not noticed ?

thank you again.

**Comment by PokemonGoSucks** [comment]
The problem might be in the signature. Try commenting out :

```
/*
        signatureBuilder.locationFix = [try! locationFix.LocationFixes[0].build(),
                                        try! locationFix.LocationFixes[1].build(),
                                        try! locationFix.LocationFixes[2].build()]

        signatureBuilder.activityStatus = getActivityStatus()
        signatureBuilder.deviceInfo = getDeviceInfo()
        signatureBuilder.sensorInfo = getSensorInfo()
*/
```

**Comment by acer915** [comment]
Hi @PokemonGoSucks , it's work. 
Very thanks.
