### ISSUE TITLE
No map objects for locations other than US and Canada

### ISSUE THREAD

**Issue by iTester321** [lsapan/pgoapi-swift#56]
I am checking on Swift3.0 version and getting following issue

ViewController.swift - didReceiveApiResponse(_:response:) - 177 - Got map objects!
however there are no forts,  spawnPoints, catchablePokemons, wildPokemons, nearbyPokemons getting in the response other than US and Canada locations.

PokemonMap.swift - viewDidLoad() - 33 - forts - 0
PokemonMap.swift - viewDidLoad() - 34 - spawnPoints - 0
PokemonMap.swift - viewDidLoad() - 35 - catchablePokemons - 0
PokemonMap.swift - viewDidLoad() - 36 - wildPokemons - 0
PokemonMap.swift - viewDidLoad() - 37 - nearbyPokemons - 0

is there any setting to check for other countries ?

am early response will be appreciated.

**Edit**: To addin this was working fine in the master version I.e. Swift 2 version.

**Comment by iTester321** [comment]
To addin this was working fine in the master version I.e. Swift 2 version.

**Comment by PokemonGoSucks** [comment]
Try setting all bools to false in setApiSettings and let me know if it works. I'll try it later tonight.

Edit: Oops, I meant setPlatformRequestSettings, not setApiSettings.

**Comment by iTester321** [comment]
@PokemonGoSucks, thanks for quick revert. I have changed the above mentioned settings at both places 1. at default and at the setPlatformRequestSettings (as this method is not been called).

Really appreciate your early advice to move forward, thanks

at default

```
internal struct platformRequestSettings {
    //    internal var useSensorInfo: Bool = true
    //    internal var useActivityStatus: Bool = true
    //    internal var useDeviceInfo: Bool = true
    //    internal var useLocationFix: Bool = true
    //    internal var randomizedTimeSnapshot = UInt64.random(100, max: 500)

    internal var useSensorInfo: Bool = false
    internal var useActivityStatus: Bool = false
    internal var useDeviceInfo: Bool = false
    internal var useLocationFix: Bool = false
    internal var randomizedTimeSnapshot = UInt64.random(100, max: 500)
}
```

at the setPlatformRequestSettings

```
open func setPlatformRequestSettings(useActivityStatus: Bool? = false, useDeviceInfo: Bool? = false, useSensorInfo: Bool? = false, useLocationFix: Bool? = false) {
    print("\(URL(fileURLWithPath: #file).lastPathComponent) - \(#function) - \(#line) - useActivityStatus: \(useActivityStatus)")
    print("\(URL(fileURLWithPath: #file).lastPathComponent) - \(#function) - \(#line) - useDeviceInfo: \(useDeviceInfo)")
    print("\(URL(fileURLWithPath: #file).lastPathComponent) - \(#function) - \(#line) - useSensorInfo: \(useSensorInfo)")
    print("\(URL(fileURLWithPath: #file).lastPathComponent) - \(#function) - \(#line) - useLocationFix: \(useLocationFix)")

    //        unknown6Settings.useActivityStatus = useActivityStatus!
    //        unknown6Settings.useDeviceInfo = useDeviceInfo!
    //        unknown6Settings.useSensorInfo = useSensorInfo!
    //        unknown6Settings.useLocationFix = useLocationFix!

    unknown6Settings.useActivityStatus = false
    unknown6Settings.useDeviceInfo = false
    unknown6Settings.useSensorInfo = false
    unknown6Settings.useLocationFix = false

}
```

However, there is no improvement. The test results are as follows:

**Failed** - Not getting any map objects for below: (**Not OK**)

```
    // London
    latField.text! = String(51.507351)
    longField.text! = String(-0.127758)

    // Eiffle Tower, Paris
    latField.text! = String(48.858370)
    longField.text! = String(2.294481)

    // Sydney Opera House
    latField.text! = String(-33.856767)
    longField.text! = String(151.215284)
```

**Passed** - getting map objects for below: (**OK**)

```
    // Apple HQ
    latField.text! = String(37.33161821509)
    longField.text! = String(-122.0298043927)

     // Time Square, Newyork
    latField.text! = String(40.759011)
    longField.text! = String(-73.984472)

    // toronto, Canada
    latField.text! = String(43.653226)
    longField.text! = String(-79.383184)
```

**Comment by PokemonGoSucks** [comment]
The problem was in xxhash, it should be solved now.

**Comment by iTester321** [comment]
thanks @PokemonGoSucks, it helped a lot !!! 👍
