### ISSUE TITLE
will it update？

### ISSUE THREAD

**Issue by oujinlong** [lsapan/pgoapi-swift#59]
thanks for working on this！
the api may be changed
I sincerely want to know that you will continue to update it
thanks

**Comment by PokemonGoSucks** [comment]
I'm no longer able to commit as much time to the project or interested in the game, but I will likely update it if #re is successful within the next few days. Apparently the fix could be as simple as changing the seeds for xxhash.

**Comment by oujinlong** [comment]
Thank you very much for your contribution.

**Comment by PokemonGoSucks** [comment]
No problem. I actually have some time again and I'm trying to see if I can get any bit of elfinlazz/hashfunc2 into swift.

**Comment by PokemonGoSucks** [comment]
The api leaked: https://gist.github.com/anonymous/0df2247292a473fd3b51c7d338d4a578

The major hurdle is still the hashing function and it's unlikely that I'll be able to convert it to Swift. Hopefully another team can get it in C or python so it wont be as hard.

**Comment by oujinlong** [comment]
I see, thank you very much for your efforts, I will continue to pay attention to you.

**Comment by oujinlong** [comment]
I don't know this will help you
https://pogodev.org/
https://github.com/eunchong/pgoapi

**Comment by PokemonGoSucks** [comment]
It's now released.

**Comment by oujinlong** [comment]
Thanks a lot!!!
