### ISSUE TITLE
Get s2CellId from ApiResponse object

### ISSUE THREAD

**Issue by flypaper0** [lsapan/pgoapi-swift#6]
How to get s2CellId from ApiResponse object.

my response.subresponses is : 
`[ mapCells[0] {
   s2CellId: 5095060386525216768 
   currentTimestampMs: 1469660046119 
}
 status: .Success
]`

**Comment by lsapan** [comment]
The library has been updated quite a bit and you should be all set now, let me know if you're still having any issues.

**Comment by nbwar** [comment]
@lsapan I'm curious about the same thing. How do I interact with the `GeneratedMessage` that is returned from the `response.subresponses` protocol buffers object?

**Comment by lsapan** [comment]
You need to cast the subresponse using `as!`. If you send me your request I can write up an example.

**Comment by nbwar** [comment]
@lsapan  I'm just using the current example and trying to parse the `getMapObjects` response

```
} else if (intent == .GetMapObjects) {
  print("Got map objects!")
  print(response.response)
  print(response.subresponses)
}
```

What should I cast it to current it is an array of `[GeneratedMessage]`

**Comment by lsapan** [comment]
@nbwar

```
let r = response.subresponses[0] as! Pogoprotos.Networking.Responses.GetMapObjectsResponse
let cell = r.mapCells[0]
print(cell.nearbyPokemons)
print(cell.wildPokemons)
print(cell.catchablePokemons)
```

**Comment by nbwar** [comment]
Exactly what i was looking for. thanks!!

**Comment by lsapan** [comment]
No problem!
