### ISSUE TITLE
API Exception: captchaRequired implementation

### ISSUE THREAD

**Issue by aliasdoc** [lsapan/pgoapi-swift#60]
Hi,

You know how to implement captcha ??

Thanks.

**Comment by PokemonGoSucks** [comment]
Use the new getChallengeURL() and verifyToken()

**Comment by aliasdoc** [comment]
Hi @PokemonGoSucks , thanks you but getChallengeURL() always returns nil

```
func didReceiveApiException(_ intent: PGoApiIntent, exception: PGoApiExceptions) {
        print("API Exception: \(exception)")
        print("API Challenge URL: \(request!.getChallengeURL())")
    }
```

**Comment by aliasdoc** [comment]
Ok, exception delegate is called before challenge url is populated, thanks.

**Comment by quangpc-zz** [comment]
@aliasdoc Could u please help me how to verify capcha in steps
after we get challenge url, we show web view for user verify capcha, then use verifyToken(), am I right?
