### ISSUE TITLE
Map objects no forts and pokemon data.

### ISSUE THREAD

**Issue by acer915** [lsapan/pgoapi-swift#61]
Hello, I use PGoApi-Example, but not any forts, pokemon data in map object array. all is 0 values.

Any idea?

Thanks.

![screen shot 2016-11-21 at 11 13 33](https://cloud.githubusercontent.com/assets/1250351/20469542/95929556-afdb-11e6-8fc7-60d6f72e5948.png)

**Comment by PokemonGoSucks** [comment]
0.47.1 was released and there's new hashing. I will not be updating anymore.

**Comment by netleave** [comment]
acer915, which location you're finding forts and pokemon…? Maybe we're facing the same issue.

**Comment by PokemonGoSucks** [comment]
The problem should be solved now.
