### ISSUE TITLE
Objective-C Support

### ISSUE THREAD

**Issue by kilabyte** [lsapan/pgoapi-swift#9]
Any plans to support objective c implementations?

**Comment by lsapan** [comment]
I wouldn't be opposed to it. My current focus when I have time is to get the project properly updated as a standalone framework with an example project. Once that's done though I'd be open to PRs to make it compatible.

**Comment by lsapan** [comment]
@kilabyte I've just finished refactoring the project quite a bit. It should now be pretty easy to make it compatible with Objective-C. Is that something you'd be willing to tackle?

**Comment by kilabyte** [comment]
Ya sure! I don't have many free cycles but I'll do what I can! 😁

**Comment by lsapan** [comment]
Great! Thanks, I feel you on the cycles thing. Let me know if you need any assistance.

**Comment by NazarYavornytskyy** [comment]
I successfully pun code from Swift lib in my Objc project, just added PogoAPI in PODs, after using bridge and some code refactoring, now seems all works fine

**Comment by kilabyte** [comment]
@NazarYavornytskyy care to share? Even when i build the framework there are no defined objc methods or initializers unless i add the objc refactoring

**Comment by lsapan** [comment]
@NazarYavornytskyy it'd be awesome if you could submit a PR with your Objective-C compatibility changes.

**Comment by NazarYavornytskyy** [comment]
@lsapan @kilabyte guys, with pleasure but currently ProtoBuf has changed, it's showstopper for me and for many people (

**Comment by kilabyte** [comment]
Submit the PR anyway as I'm sure we'll update the proto when the fix it out. Or submit it as a new branch

**Comment by NazarYavornytskyy** [comment]
ok, will do after my vacation )
